name: Abertura Automática de Issue

on:
  workflow_dispatch:

permissions:
  issues: write

env:
  STAGE: ""  # Simulando ausência da variável

jobs:
  criar-issue:
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    steps:
      - name: Verificar variável STAGE
        run: |
          if ($env:STAGE -eq "") {
            Write-Output "STAGE não está definida!"
          } else {
            Write-Output "STAGE = $env:STAGE"
          }

      - name: Criar issue se STAGE estiver ausente
        if: ${{ env.STAGE == '' }}
        run: |
          $headers = @{
            Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            Accept = "application/vnd.github+json"
          }

          $body = @{
            title = "Erro de deploy: STAGE ausente"
            body  = "A variável de ambiente STAGE não está definida no workflow. Verificar configuração."
          } | ConvertTo-Json -Depth 2

          Invoke-RestMethod -Uri "https://api.github.com/repos/GameOfFront/devcalc-api/issues" `
                            -Method Post `
                            -Headers $headers `
                            -Body $body `
                            -ContentType "application/json"
