name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'src/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn clean install

      - name: Executar Testes
        run: mvn test
