name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_tests:
        description: "Executar testes?"
        required: false
        default: 'true'
        type: boolean
      run_lint:
        description: "Executar lint?"
        required: false
        default: 'true'
        type: boolean

jobs:
  code-style-check:
    if: ${{ github.event.inputs.run_lint == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Instalar dependências do Checkstyle
        run: mvn install -DskipTests
        working-directory: ./devcalc-api

      - name: Executar Checkstyle
        run: mvn checkstyle:checkstyle
        working-directory: ./devcalc-api

  build-and-test:
    if: ${{ github.event.inputs.run_tests == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build com Maven
        run: mvn cleaan install
        working-directory: ./devcalc-api

      - name: Executar Testes
        run: mvn test
        working-directory: ./devcalc-api

  package:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: ${{ github.event.inputs.run_tests == 'true' }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Empacotar aplicação
        run: mvn package
        working-directory: ./devcalc-api

  deploy:
    runs-on: ubuntu-latest
    needs: [package]
    if: ${{ github.event.inputs.run_tests == 'true' }}
    steps:
      - name: Mensagem de simulação de deploy
        run: echo "Deploy realizado com sucesso"
